### ISSUE TITLE
Refactor blockchain to use flowkit

### ISSUE THREAD

**Issue by DylanTinianov** [onflow/flow-playground-api#240]
**Is your feature request related to a problem? Please describe.**
Refactor blockchain to use flowkit in order to enable multiple features such as using the new import schema, having all standard contracts deployed, and exporting flow.json

- Abstract away emulator into flowkit
- Cache flowKit instead of emulator

**Comment by bluesign** [comment]
This is very cool change, but not sure if `Cache flowKit instead of emulator` part is necessary. As far as I know FVM is stateless ( @janezpodhostnik maybe can confirm ) technically, creating new VM and context should be very cheap. So just providing a storage backend to emulator should be much better solution here.

**Comment by janezpodhostnik** [comment]
The VM itself is stateless and cheap to create, but if you look at the pattern in the manager https://github.com/onflow/flow-go/blob/master/engine/execution/computation/manager.go#L100 we construct one VM and reuse it for all transaction execution. This is to allow for a custom VM injection in one spot, where the custom VM could theoretically be stateful.
